export const customers = [
  {
    id: 'C-1001',
    name: 'Smith Residence',
    contact: 'John Smith',
    phone: '555-123-4567',
    email: 'john@example.com',
    address: '123 Main St',
    notes: 'Prefers morning appointments.',
  },
  {
    id: 'C-1002',
    name: 'Acme Office',
    contact: 'Sarah Jones',
    phone: '555-987-6543',
    email: 'sarah@acme.com',
    address: '800 Business Pkwy',
    notes: 'Coordinate work around office hours.',
  },
  {
    id: 'C-1003',
    name: 'Johnson Home',
    contact: 'Mark Johnson',
    phone: '555-222-8899',
    email: 'mark@example.com',
    address: '45 Oak Drive',
    notes: 'Has multiple active home projects.',
  },
];

export const projects = [
  {
    id: 'P-1001',
    customerId: 'C-1001',
    customer: 'Smith Residence',
    name: 'Kitchen Remodel',
    status: 'In Progress',
    assignedTo: 'Mike',
    progress: 65,
    targetCompletion: '2026-06-15',
  },
  {
    id: 'P-1002',
    customerId: 'C-1002',
    customer: 'Acme Office',
    name: 'Conference Room Buildout',
    status: 'Scheduled',
    assignedTo: 'Sarah',
    progress: 20,
    targetCompletion: '2026-06-28',
  },
  {
    id: 'P-1003',
    customerId: 'C-1003',
    customer: 'Johnson Home',
    name: 'Basement Finish',
    status: 'In Progress',
    assignedTo: 'Chris',
    progress: 45,
    targetCompletion: '2026-07-10',
  },
];

export const timeEntries = [
  {
    id: 'T-001',
    projectId: 'P-1001',
    user: 'Mike',
    submittedAt: '2026-05-08 2:43 PM',
    hours: 4.5,
    workCompleted: 'Mainline',
    vehicle: '2016 Ford Van',
    notes: 'Completed mainline service and cleanup.',
  },
  {
    id: 'T-002',
    projectId: 'P-1001',
    user: 'Mike',
    submittedAt: '2026-05-07 11:10 AM',
    hours: 3,
    workCompleted: 'Lateral',
    vehicle: '2007 Ford F-150',
    notes: 'Worked on lateral access and inspection.',
  },
];